#querying from dependency track list of projects
name: Dependency Track


on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1


    - name: Query from DT
      env:
        DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEP_TRACK_TOKEN }}
      run: |
        curl -H "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" https://sbom.eclipse.org/dashboard:8081/api/v1/project


