#querying from dependency track list of projects
name: Dependency Track


on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2


    - name: Query from DT
      env:
        DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEP_TRACK_TOKEN }}
      run: |
        curl -s -H "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" https://sbom.eclipse.org/api/v1/vulnerability/project/3fe77d48-737b-4d3f-9edc-3e6c4287069c
